# Θέλουμε set αντί για list ή dict διότι
# 1. Το κάθε item στην λίστα είναι μοναδικό
# 2. Κάνουμε μόνο check ύπαρξης tag μέσα σε αυτά τα sets κάτι που τα set κάνουν πιο γρήγορα
# 3. Δεν μας αφορά η σειρά με την οποία βρίσκονται τα tags.
VALID_TAG_IDENTIFIERS = {
    'Event',
    'Site',
    'Date',
    'Round',
    'White',
    'Black',
    'Result',
    'WhiteTitle',
    'BlackTitle',
    'WhiteElo',
    'BlackElo',
    'WhiteUSCF',
    'BlackUSCF',
    'WhiteNA',
    'BlackNA',
    'WhiteType',
    'BlackType',
    'EventDate',
    'EventType',
    'EventRounds',
    'EventCountry',
    'EventSponsor',
    'Section',
    'Stage',
    'Board',
    'Opening',
    'Variation',
    'SubVariation',
    'ECO',
    'NIC',
    'Time',
    'UTCTime',
    'UTCDate',
    'TimeControl',
    'SetUp',
    'FEN',
    'Termination',
    'Annotator',
    'Mode',
    'PlyCount',
    'WhiteRatingDiff',
    'BlackRatingDiff',
    'Variant'
} 
REQUIRED_TAG_IDENTIFIERS = {
    'Event',
    'Site',
    'White',
    'Black',
    'Result',
}